### PR TITLE
Upgrade to new yaml-cpp interface. All tests perform the same as the head of master branch

### PR DESCRIPTION
**Pull request by gantech**
Rtest Begin:
..periodic3dElemNp1........... PASSED:  6.8  s
..periodic3dElemNp4........... PASSED:  2.6  s
..periodic3dElemNp8........... PASSED:  1.7  s
..periodic3dEdgeNp1........... PASSED:  3.2  s
..periodic3dEdgeNp4........... PASSED:  1.6  s
..periodic3dEdgeNp8........... PASSED:  1.1  s
..quad9HC..................... PASSED:  54.5  s
..steadyTaylorVortex.......... PASSED:  72.8  s
..hoVortex.................... PASSED:  86.0  s
..hoHelium.................... PASSED:  392.5  s
..dgNonConformal.............. PASSED:  2.8  s
..dgNonConformalEdge.......... PASSED:  2.9  s
..dgNonConformalFluids........ PASSED:  54.4  s
..dgNonConformalFluidsEdge.... PASSED:  45.7  s
..dgNonConformal3dFluids...... PASSED:  73.5  s
..dgNonConformal3dFluidsP1P2.. FAILED:  162.6  s   max diff:  .00000000000000557521999997363538
..dgNonConformal3dFluidsHexTet.FAILED:  86.8  s   max diff:  .00000000194418081000034771634727
..dgNonConformalThreeBlade.... PASSED:  53.8  s
..overset..................... PASSED:  0.7  s
..oversetFluids............... PASSED:  20.2  s
..oversetFluidsEdge........... PASSED:  13.0  s
..concentricRad............... PASSED:  22.0  s
..movingCylinder.............. PASSED:  8.3  s
..elemBackStepLRSST........... PASSED:  6.5  s
..ductWedge................... PASSED:  2.6  s
..heatedBackStep.............. PASSED:  123.4  s
..edgePipeCHT................. PASSED:  5.0  s
..elemPipeCHT................. PASSED:  9.2  s
..heliumPlume................. PASSED:  267.5  s
..edgeContact3D............... PASSED:  83.7  s
..dgNonConformalEdgeCylinder.. PASSED:  86.8  s
..fluidsPmrChtPeriodic........ PASSED:  85.5  s
..nonIsoElemOpenJet........... PASSED:  29.1  s
..nonIsoEdgeOpenJet........... PASSED:  14.0  s
..elemHybridFluids............ PASSED:  69.3  s
..elemHybridFluidsShift....... PASSED:  55.1  s
..edgeHybridFluids............ PASSED:  46.0  s
..elemClosedDomain............ PASSED:  0.9  s
..mixedTetPipe................ PASSED:  21.0  s
..inputFireElem............... PASSED:  45.6  s
..nonIsoNonUniformElemOpenJet. PASSED:  94.9  s
..nonIsoNonUniformEdgeOpenJet. PASSED:  38.5  s
..milestoneRun................ PASSED:  72.6  s
..heatedWaterChannel.......... PASSED:  46.3  s
..variableDensMMS............. PASSED:  107.6  s
..actuatorLine................ PASSED:  44.5  s
..femHC....................... PASSED:  3.0  s
..ablUnstableEdge............. PASSED:  26.4  s
..unit_tests-np1.............. PASSED
..unit_tests-np2.............. PASSED
Rtest End
Performance Rtest Begin:
..waleElemXflowMixFrac3.5m.... PASSED:  358.1  s
..uqSlidingMesh............... PASSED:  257.8  s
..uqSlidingMeshDG............. PASSED:  271.0  s
..oversetHybrid............... PASSED:  538.5  s
Performance Rtest End

### CODE REVIEW

**Comment by spdomin** [comment]
Are the diffs exactly the same between your new YAML gcc build and the old YAML with your same gcc build?

**Comment by gantech** [comment]
The old YAML gcc build has the same diffs to the last printed number on the diff. I've copied the diff from the old YAML build here

..dgNonConformal3dFluidsP1P2.. FAILED:  164.5  s   max diff:  .00000000000000557521999997363538
..dgNonConformal3dFluidsHexTet.FAILED:  87.1  s   max diff:  .00000000194418081000034771634727

**Comment by spdomin** [comment]
I think that spending some time on understanding the error checking would be useful. I want to make sure that we do not destabilize the parsing and have some sort of safety net. I am getting to the pull request - probably will be tomorrow... 

Please send me the link for the proper YAML clone. Also, have you built this on Intel to see if the warnings about smart pointers was removed? Also, gcc showed some boost issues..

I should get to this tomorrow..

**Comment by gantech** [comment]
Ok.. I made one more commit to remove #include<boost/lexical_cast> in a few files and one more unused variable. Removes a few more warnings during compile. Ran the full test suite again. Ready to merge with master.

**Pull request merged**
