### PR TITLE
corrected typo in equation 15.2

### PR DESCRIPTION
**Pull request by kilojoules**
d/dt -> d/dx_j

### CODE REVIEW

**Comment by gantech** [comment]
Thanks @kilojoules. Could you edit eqn. 15.3 too?

**Comment by kilojoules** [comment]
@gantech OK I added another commit for that

**Comment by spdomin** [comment]
Greetings @gantech and @kilojoules. Many thanks for these changes. You probably meant to deploy these changes to Nalu-Wind docs, right? My plan will be to remove the wind section soon so that users know to view Nalu-Wind.

best,

Stefan

**Comment by kilojoules** [comment]
Thanks Stefan. I made a new PR to correct these typos on the nalu-wind repo: https://github.com/Exawind/nalu-wind/pull/57

**Pull request merged**
