### PR TITLE
Fix for ParaView Catalyst regression tests

### PR DESCRIPTION
**Pull request by tjotaha**
Added Catalyst script line for CMake configure.

### CODE REVIEW

**Comment by tjotaha** [comment]
@jrood-nrel thanks for fixing my last merge request. I ran the Catalyst tests, and noticed there was a missing line to reference the Catalyst script in the Nalu input deck when it is configured by CMake.

**Comment by jrood-nrel** [comment]
@tjotaha Is `CATALYST_FILE_INPUT_DECK_COMMAND` actually necessary? I didn't see it referenced anywhere after it was set in the initial commits for Catalyst so I removed it.

**Comment by tjotaha** [comment]
@jrood-nrel The CATALYST_FILE_INPUT_DECK_COMMAND variable gets set to a string when CMake runs. This string is then substituted in the *.i.in file on the next line during the configure_file(). This produces a Nalu input deck *.i file that will invoke Catalyst when run instead of the normal Nalu Exodus 2 output.

**Comment by jrood-nrel** [comment]
Ah yes. Ok, great. Thanks! I will merge it.

**Pull request merged**
