### PR TITLE
Prototype for pre-iteration work to be performed before solve_and_update

### PR DESCRIPTION
**Pull request by sayerhs**
Add a vector of AlgorithmDrivers in EquationSystem that is used to
perform pre-iteration work across all EQS before entering
solve_and_update.

Add an overset pre-iteration work used to update field data of ghosted
elements, and the interpolated field values on fringe nodes, at the
beginning of timestep due to mesh motion that could introduce changes in
receptor node to donor element pairs.

### CODE REVIEW

**Comment by sayerhs** [comment]
@spdomin A WIP design based on our discussion regarding pre-iteration work. Take a look at the design and see if there are issues you see with this. 

The next question I have for you is how do we want to deal with the `isInit` blocks when doing `diffFluxCoeffAlgDriver_` etc to pre-iter-work.

**Comment by sayerhs** [comment]
@spdomin: Updated `EquationSystems` and `EquationSystem` to support pre/post iteration work at two stages. The new design will support the following mode of execution that we had discussed:

```
EquationSystems::pre_iter_work

for iter in num_outer_iterations:
    EquationSystem::pre_iter_work
    EquationSystem::solve_and_update
    EquationSystem::post_iter_work

EquationSystems::post_iter_work
```

Moved the _overset fringe update_ to `EquationSystems::pre_iter_work`.

**Comment by spdomin** [comment]
Looking really close.. How about this:

```
//--------------------------------------------------------------------------
//-------- solve_and_update ------------------------------------------------
//--------------------------------------------------------------------------
bool
EquationSystems::solve_and_update()
{
  // Perform necessary setup tasks before iteration over all equations
  pre_iter_work();

  EquationSystemVector::iterator ii;
  for( ii=equationSystemVector_.begin(); ii!=equationSystemVector_.end(); ++ii )
  {
    (*ii)->pre_iter_work();
    (*ii)->solve_and_update();
    (*ii)->pre_iter_work();
  }

  // memory diagnostic
  if ( realm_.get_activate_memory_diagnostic() ) {
    NaluEnv::self().naluOutputP0() << "NaluMemory::EquationSystem::solve_and_update()" << std::endl;
    realm_.provide_memory_summary();
  }

  // FIXME: Refactor EquationSystem::post_iter_work
  for( ii=equationSystemVector_.begin(); ii!=equationSystemVector_.end(); ++ii )
    (*ii)->post_iter_work_deprecated();

  // Perform necessary setup tasks after iteration over all equations
  post_iter_work();

  // check equations for convergence
  bool overallConvergence = true;
  for( ii=equationSystemVector_.begin(); ii!=equationSystemVector_.end(); ++ii ) {
    const bool systemConverged = (*ii)->system_is_converged();
    if ( !systemConverged )
      overallConvergence = false;
  }
  
  return overallConvergence;
}

```

**Comment by sayerhs** [comment]
@spdomin Final updates incorporating all changes based on our discussion. Also updated the overset gold norm files. All other tests pass as is expected.

**Pull request merged**
