### PR TITLE
Fix residual reporting for HYPRE solver interface.

### PR DESCRIPTION
**Pull request by sayerhs**
- HYPRE non-linear residual reporting was incorrect in the original
  implementation because it reported the norm of the solution vector
  instead of the RHS. This meant that the residuals reported were quite
  different from those reported by TpetraLinearSystem even when the
  solvers converged to the same solution.

- Previous reporting used relative residuals when reporting HYPRE linear
  residuals. For compatibility with TpetraLinearSystem residual
  reporting, the code has been modified to report final linear residual
  upon convergence within HypreLinearSystem.

- Rebless norm gold file because mean system norms have changed.

Only the residuals reported in the log file is affected by this change.
Users should not see any change in the number of linear iterations
and/or time to solution, or the actual physical variables due to this
change.

### CODE REVIEW

**Comment by sayerhs** [comment]
Residuals reported for `dgNonConformalThreeBlade` test case by Belos/Muelu and HYPRE 

```
==> Belos GMRES + Muelu <==
        ContinuityEQS         10       0.000163264       0.080731             1
        ContinuityEQS          9       7.62267e-05      0.0457237      0.566371
        ContinuityEQS         11       6.14885e-05      0.0603936             1
        ContinuityEQS         10       1.41042e-05      0.0134475      0.222664
        ContinuityEQS         11       2.31496e-05      0.0308881             1
        ContinuityEQS          9        2.2629e-05      0.0142486      0.461299
        ContinuityEQS          9       2.05892e-05      0.0233856             1
        ContinuityEQS          9        7.3608e-06      0.0116949      0.500089
        ContinuityEQS          8       3.25919e-05      0.0154034             1
        ContinuityEQS          8       1.30612e-05     0.00595331      0.386493
        ContinuityEQS          8       1.80035e-05     0.00951783             1
        ContinuityEQS          9       1.33055e-06     0.00256528      0.269524
        ContinuityEQS          9       5.17721e-06     0.00618278             1
        ContinuityEQS          9       9.62033e-07     0.00146745      0.237345
        ContinuityEQS          9        3.9427e-06     0.00186844             1
        ContinuityEQS          9       7.77573e-07    0.000673989      0.360723
        ContinuityEQS         10        1.0609e-06    0.000937824             1
        ContinuityEQS          9       5.98494e-07    0.000455095      0.485267
        ContinuityEQS         10       9.32573e-07    0.000812891             1
        ContinuityEQS          9       5.05124e-07    0.000455771      0.560679

==> HYPRE GMRES + BoomerAMG <==
        ContinuityEQS          6       8.89819e-05       0.080731             1
        ContinuityEQS          5       2.31319e-05      0.0457235      0.566369
        ContinuityEQS          6       8.79687e-05      0.0603935             1
        ContinuityEQS          5       1.82365e-05      0.0134473      0.222662
        ContinuityEQS          6       3.46275e-05       0.030888             1
        ContinuityEQS          5       5.10476e-06      0.0142486      0.461299
        ContinuityEQS          4       4.08461e-05      0.0233856             1
        ContinuityEQS          4       7.04585e-06      0.0116949      0.500089
        ContinuityEQS          3       1.57221e-05      0.0154035             1
        ContinuityEQS          3       5.84172e-06     0.00595332      0.386492
        ContinuityEQS          3       7.43427e-06     0.00951789             1
        ContinuityEQS          4       1.11996e-06     0.00256528      0.269522
        ContinuityEQS          3       8.89247e-06     0.00618278             1
        ContinuityEQS          4       7.98419e-07     0.00146745      0.237344
        ContinuityEQS          4       2.32954e-06     0.00186844             1
        ContinuityEQS          4       6.77712e-07    0.000673979      0.360718
        ContinuityEQS          5       4.02791e-07    0.000937814             1
        ContinuityEQS          4       7.27921e-07     0.00045509      0.485267
        ContinuityEQS          4       1.67696e-06    0.000812885             1
        ContinuityEQS          4        5.4457e-07    0.000455769       0.56068
```

**Comment by sayerhs** [comment]
Residuals reported for ABL neutral precursor simulation (`5x5x1 km` mesh with `40m` uniform resolution) - [first two timesteps with 3 outer iterations]

```
==> Trilinos solver stack for all EQS <==
        MomentumEQS            2            133453         493646             1
        ContinuityEQS          6           36.3607        116.781             1
        TurbKineticEnergyEQS   2           12.3594        100.057             1
        EnthalpyEQS            2           7067.13        82258.3             1
        MomentumEQS            3           4.77854        450.413   0.000912421
        ContinuityEQS          8           0.10599       0.488996    0.00418729
        TurbKineticEnergyEQS   2            0.4899        3.44505     0.0344311
        EnthalpyEQS            2           33.4986        210.105    0.00255421
        MomentumEQS            4        0.00580681        12.7943   2.59179e-05
        ContinuityEQS         12       1.38102e-05      0.0616241   0.000527689
        TurbKineticEnergyEQS   4       8.37422e-07      0.0551459   0.000551148
        EnthalpyEQS            3        0.00165655        4.54196   5.52158e-05
        MomentumEQS            2           33344.6         246759             1
        ContinuityEQS          5           5.12078        16.9756             1
        TurbKineticEnergyEQS   2           11.5184        159.389             1
        EnthalpyEQS            2           6409.57         123016             1
        MomentumEQS            2           44.3081        144.261   0.000584623
        ContinuityEQS          8         0.0519438       0.245666     0.0144717
        TurbKineticEnergyEQS   2          0.317116        4.22529     0.0265093
        EnthalpyEQS            2           8.11413        150.975    0.00122728
        MomentumEQS            4       0.000288043        1.19405   4.83893e-06
        ContinuityEQS         12       2.26462e-06     0.00739245   0.000435474
        TurbKineticEnergyEQS   4       1.32487e-07      0.0444864   0.000279105
        EnthalpyEQS            3       0.000137774       0.435913   3.54355e-06

==> HYPRE solver stack for all EQS <==
        MomentumEQS            4           258.328         493646             1
        ContinuityEQS          6          0.337512        116.779             1
        TurbKineticEnergyEQS   1       0.000224581        100.057             1
        EnthalpyEQS            1          0.106544        82259.3             1
        MomentumEQS            4          0.289042        399.883    0.00081006
        ContinuityEQS          6       0.000176664      0.0430027   0.000368239
        TurbKineticEnergyEQS   1       8.15908e-06        3.44421     0.0344223
        EnthalpyEQS            1        0.00019401        150.424    0.00182865
        MomentumEQS            4        0.00068436        1.02467   2.07571e-06
        ContinuityEQS          4       4.76223e-05     0.00865628    7.4125e-05
        TurbKineticEnergyEQS   1       1.45815e-07      0.0530407   0.000530103
        EnthalpyEQS            1        6.9568e-08      0.0148565   1.80606e-07
        MomentumEQS            3           1068.96         246759             1
        ContinuityEQS          5         0.0170996        16.9738             1
        TurbKineticEnergyEQS   1         0.0161387         159.39             1
        EnthalpyEQS            1           11.4722         123016             1
        MomentumEQS            3          0.656803        134.633   0.000545605
        ContinuityEQS          6       7.19922e-05      0.0321591    0.00189463
        TurbKineticEnergyEQS   1        0.00043133        4.22504     0.0265077
        EnthalpyEQS            1         0.0139426        149.882    0.00121839
        MomentumEQS            3        0.00201273       0.381437   1.54579e-06
        ContinuityEQS          4       1.15766e-05     0.00198233   0.000116788
        TurbKineticEnergyEQS   1       5.02735e-06      0.0444048   0.000278593
        EnthalpyEQS            1       1.34671e-06     0.00692067   5.62582e-08
```

**Comment by spdomin** [comment]
@jrood-nrel, do you feel comfortable with moving forward with pull requests or do you still need time to resolve the Trilinos/Nalu issues? Most of the pull requests, such as this one, seem orthogonal. With only one fail, we might feel okay with moving forward. Before, we saw widespread fails that was a bit worrisome.

**Comment by jrood-nrel** [comment]
@spdomin Currently I have OpenMP shut off for all machines and all tests. This seems to bring the default behavior back, which means `nrel5MWactuatorLine` should be failing on OSX due to expectation of loading a `.so` and `ablNeutralEdge` should be failing on Merlin due to a very minor diff. The one thing I'm worried about and investigating today is why the `unitTest1` is failing only on Peregrine with the intel compiler with OpenMP off. If I turn OpenMP on, we will go back to ~17 diffing tests on Linux and ~60 segfaulting tests with GCC 7.2.0. I would be fine merging pull requests with OpenMP off for now since my pull request should solve 1 failing test and the Linux/Peregrine/GCC case is clean.

**Pull request merged**
