### PR TITLE
Added the CoriolisSrc class

### PR DESCRIPTION
**Pull request by mbarone81**
* The CoriolisSrc class contains the setup data and calculations for the
   Coriolis source term.  This prevents code duplication between the Node and
   Element source term algorithms.  Each of these algorithms will now contain
   a CoriolisSrc object with the necessary data.

### CODE REVIEW

**Comment by mbarone81** [comment]
This pull request has a clean commit history.  I think I have figured out my workflow issues.

**Comment by spdomin** [comment]
This is a WIP, right? You cleaned up the NodeSrcAlg and now will deploy the generalized CoriolisSrc class infrastructure to the ElemSrcAlg class, right?

Looks nice and clean...

**Comment by spdomin** [comment]
@mbarone81, can you check your usage of tabs in your editor? I see code like the following:
```
        else if ( sourceName == "actuator_line") {
          suppAlg = new MomentumActuatorLineSrcNodeSuppAlg(realm_);
        }
else if ( sourceName == "EarthCoriolis") {
   suppAlg = new MomentumCoriolisSrcNodeSuppAlg(realm_);
}
        else {
          throw std::runtime_error("MomentumNodalSrcTerms::Error Source term is not supported: " + sourceName);
        }
```

**Comment by mbarone81** [comment]
Yes @spdomin it is a WIP and I will proceed to ElemSrcAlg.  Cleaned up some tabs,  will try to be neater ;-)

**Pull request merged**
