### PR TITLE
docs: updated patch to spack packages

### PR DESCRIPTION
**Pull request by aprokop**
@jrood-nrel

### CODE REVIEW

**Comment by jrood-nrel** [comment]
Thanks! I forgot I reorganized my repo and I have to update all the references to everything pointing to it. I might wait to update all the references though because I think the plan is to move my repo to this org soon.

**Comment by aprokop** [comment]
Sure. When is the move scheduled for?

**Comment by jrood-nrel** [comment]
I think my repo is ready to move. My guess is it will happen next Monday when we have our next meeting at NREL. I will try to update all the references to my repo in the meantime.

**Comment by aprokop** [comment]
No need for this PR if the repo is going to move anyway. Will check the refs after the merge.

**Pull request closed without merging**
