### PR TITLE
Update header file locations of STK fixtures.

### PR DESCRIPTION
**Pull request by jrood-nrel**
This should fix the errors involving the change of STK header file locations in Trilinos once the fix in https://github.com/trilinos/Trilinos/issues/1433 is merged. Probably doesn't make much difference if we merge this PR now or after the Trilinos fix is merged.

### CODE REVIEW

**Comment by spdomin** [comment]
One simple question... If we merge this now, the current builds that are working with an older Trilinos installation will start failing, right? However, if the update of Trilinos occurs, then Nalu will start failing. I would vote that we process this pull request when Nalu starts failing.

**Comment by jrood-nrel** [comment]
Ah, right. I'm so used to using the absolute latest Trilinos. Agreed.

**Comment by spdomin** [comment]
I think you are running the latest Trilinos with the set of patches provided. Once the update of STK is made in Trilinos and provided to develop, your PR should follow.

**Comment by jrood-nrel** [comment]
Trilinos has implemented the fix in the develop branch and it's after the Q3 milestone so I am going to merge this.

**Pull request merged**
